name: SSH Tunnel
description: Create SSH tunnel to public server
url: https://github.com/AlexxIT/hassio-addons/tree/master/ssh_tunnel
arch: [ amd64, aarch64, i386, armv7, armhf ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.0.7
slug: ssh_tunnel
init: false
startup: system
host_network: true
options:
  ssh_host: 123.123.123.123
  ssh_user: root
  ssh_port: 22
  # Удалены tunnel_http и tunnel_https
  tunnel_ports: # Новый параметр для кастомных портов, например, ["80:80", "443:8443"]
  socks_port: 1080
schema:
  ssh_host: "str"
  ssh_user: "str"
  ssh_port: "int"
  # Удалены tunnel_http: "bool" и tunnel_https: "bool"
  tunnel_ports:
    - str
  socks_port: "int"
  advanced: "str?"
  before: "str?"
